base_configs:
  # file configs:
  train_file: /mnt/cephfs_wj/common/lab/baoyu.nlp/data/quora-for-tree-ae/train.bin
  dev_file: /mnt/cephfs_wj/common/lab/baoyu.nlp/data/quora-for-tree-ae/dev.bin
  test_file: /mnt/cephfs_wj/common/lab/baoyu.nlp/data/quora-for-tree-ae/test.bin
  vocab: /mnt/cephfs_wj/common/lab/baoyu.nlp/data/quora-for-tree-ae/vocab.bin
  eval_lists: ~
#  logdir: /mnt/cephfs_wj/bytetrans/baoyu.nlp/experiments/logs
#  model_dir: /mnt/cephfs_wj/bytetrans/baoyu.nlp/experiments/models
  logdir: /data00/home/baoyu.nlp/run_logs
  model_dir: /data00/home/baoyu.nlp/run_models
  exp_name: ~
  task_type: AutoEncoder
  # train configs
  start_iter: 0
  batch_size: 50
  log_every: 50
  dev_every: 1000
  lr: 0.0005
  lr_decay: 0.5
  patience: 20
  clip_grad: 5.0
  reset_optimizer: false